### ISSUE TITLE
Scenario outline title displays parameter name instead of its value in allure report: wdio-allure-reporter

### ISSUE THREAD

**Issue by pratyavi** [webdriverio-boneyard/wdio-allure-reporter#135] opened 2018-08-24 06:10 UTC
I am using wdio-allure-reporter and using scenario outline in the feature file

Scenario Outline: test language translation
   Given User is on homepage
   When select <language> from langauge dropdown
   Then language changed and <Text> is visible in selected language

   Examples:
            | language | Text    |
            | Deutsch  | Home    |
            | Dansk    | Hjem    |
            | Magyar   | Otthon  |

When I execute this scenario using  "npm test" and generate allure report . I see parameter value in scenario outline title in report. In XML also the parameter name is coming not its value.

How it can be resolved?

![allure](https://user-images.githubusercontent.com/42466160/44567961-505aec80-a792-11e8-9f39-1da3f7a87ce7.PNG)
![xml](https://user-images.githubusercontent.com/42466160/44567998-75e7f600-a792-11e8-942a-af2ef06c6ca1.PNG)

**Comment by BorisOsipov** [comment] 2018-08-24 08:26
Duplicate of https://github.com/webdriverio/wdio-cucumber-framework/issues/142

**Closed by BorisOsipov** 2018-08-24 08:26 UTC
